# Generated by Django 3.1.7 on 2021-03-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('artist', models.CharField(max_length=40)),
                ('spotify_id', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('songs', models.ManyToManyField(to='vibes_interface.Song')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
